// TODO: Will need different lists of enemies and bosses, probably separated by level or something
export const enemies = [
    {
      name: 'Goblin',
      health: 15,
      maxHealth: 15,
      strength: 2,
      defense: 5,
      speed: 80,
      mana: 0,
      maxMana: 0,
      accuracy: 60,
      luck: 2,
      resistance: 10,
      effects: [],
      turnCount: 0,
      ATB: 0
    },
    {
      name: 'Green Slime',
      health: 3,
      maxHealth: 3,
      strength: 2,
      defense: 0,
      speed: 75,
      mana: 0,
      maxMana: 0,
      accuracy: 60,
      luck: 2,
      resistance: 10,
      effects: [],
      turnCount: 0,
      ATB: 0
    },
    {
      name: 'Red Slime',
      health: 6,
      maxHealth: 6,
      strength: 3,
      defense: 0,
      speed: 70,
      mana: 0,
      maxMana: 0,
      accuracy: 50,
      luck: 2,
      resistance: 10,
      effects: [],
      turnCount: 0,
      ATB: 0
    },
    {
      name: 'Kobold',
      health: 4,
      maxHealth: 4,
      strength: 2,
      defense: 5,
      speed: 90,
      mana: 10,
      maxMana: 0,
      accuracy: 60,
      luck: 2,
      resistance: 10,
      effects: [],
      turnCount: 0,
      ATB: 0
    },
    {
      name: 'Giant',
      health: 35,
      maxHealth: 35,
      strength: 8,
      defense: 4,
      speed: 50,
      mana: 0,
      maxMana: 0,
      accuracy: 50,
      luck: 2,
      resistance: 10,
      effects: [],
      turnCount: 0,
      ATB: 0
    }
  ];